server:
  servlet:
    context-path: /api/princing
  port: 8080

spring:
  application:
    name: pricing-api
  datasource:
    url: jdbc:h2:mem:princing
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    root: INFO
    com.waltercrdz.api: INFO